import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'

import { cn } from '@/lib/utils'
import Header from './components/Header'
import SideMenu from './components/SideMenu'
import { SideBarProvider } from './context/sideBarContext'
import MainContentWrapper from './components/MainContentWrapper'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Teste técnico Federação Paulista de Futebol',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased mt-14 no-scrollbar',
          fontSans.variable,
        )}
      >
        <SideBarProvider>
          <Header />
          <SideMenu />
          <MainContentWrapper>{children}</MainContentWrapper>
        </SideBarProvider>
      </body>
    </html>
  )
}
